def num_function(num):    
    print(num, end = '')
num_function (8)
num_function (8)
num_function (0)
num_function (0)
num_function (5)
num_function (5)
num_function (5)
num_function (3)
num_function (5)
num_function (3)
num_function (5)